<?php
/**
 * Test class for parallely_Transport_File.
 * Generated by PHPUnit on 2012-03-24 at 14:59:34.
 */
namespace parallely\Test\Transport;

class ApcTest extends \parallely\Test\Transport\TestAbstract {

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    public function setUp() {
        var_dump(extension_loaded('apc'));
        var_dump(ini_get('apc.enabled'));
        var_dump(ini_get('apc.enable_cli'));
        if (extension_loaded('apc') === true and (bool)ini_get('apc.enabled') === true and (bool)ini_get('apc.enable_cli') === true) {
            $this->_sTestClass = '\\parallely\\Transport\\Apc';
            $this->_oOptions = new \stdClass();

            parent::setUp();
        }
        else {
            $this->markTestSkipped('Test skipped, as apc is not installed');
        }
    }
}
